apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-tempo-creds
  namespace: tracing-system
stringData:
  access_key_id: admin
  access_key_secret: key
  bucket: tempo-traces
  endpoint: http://seaweedfs-s3.seaweedfs-s3.svc:8333
type: Opaque