apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxform-renderer
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taxform-renderer
  template:
    metadata:
      labels:
        app: taxform-renderer
    spec:
      containers:
        - name: taxform-renderer
          image: default-route-openshift-image-registry.apps-crc.testing/sandbox/tax-form-renderer:1776645686
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: otel-collector.sandbox.svc:4317
---
apiVersion: v1
kind: Service
metadata:
  name: taxform-renderer
  namespace: sandbox
spec:
  selector:
    app: taxform-renderer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: taxform-renderer
  namespace: sandbox
spec:
  to:
    kind: Service
    name: taxform-renderer
  port:
    targetPort: http
