apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: sandbox
spec:
  mode: deployment # deployment, daemonset, statefulset, sidecar
  config:
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector-scrape-todo'
              static_configs:
                - targets: ['todo-api.sandbox.svc:8080']
      otlp:
        protocols:
          grpc: {}
          http: {}
      zipkin: {}
    processors:
      batch: {}
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 30
      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.namespace.name
            - k8s.deployment.name
      attributes:
        actions:
          - key: "scraped_by"
            value: "otel-collector-ozwalsh"
            action: insert
    exporters:
      debug:
        verbosity: detailed
      otlp/tempo:
        endpoint: tempo-tracing-system-tempo-stack.tracing-system.svc:4317
        tls:
          insecure: true
        headers:
          X-Scope-OrgID: dev
      prometheus:
        endpoint: "0.0.0.0:8889"
    service:
      pipelines:
        traces:
          receivers: [otlp, zipkin]
          processors: [memory_limiter, batch]
          exporters: [otlp/tempo, debug]
        metrics:
          receivers: [prometheus, otlp]
          processors: [k8sattributes, attributes, memory_limiter, batch]
          exporters: [prometheus, debug]
