apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    oauth-apiserver.openshift.io/secure-token-storage: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2026-01-29T14:50:02Z"
  generation: 1
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: b36be575-bb88-482d-855b-353fd3f9ee60
  resourceVersion: "816"
  uid: 2d515408-9f66-48ff-a3f4-9a2638f1db2f
spec:
  audit:
    profile: Default
